# This workflow will help you build, (test) and deploy the new release on GitHub using Actions
name: Flutter CI/CD

# When the WorkFlow should run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is one or more jobs that run sequentially or in parallel
jobs:
  build:
    # The Machine we will use
    runs-on: ubuntu-latest
    steps:
      - name: Download Reposotory 
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Import Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '1.8'

      - name: Import Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.5'

      - run: flutter pub get
      # - run: flutter test

      - name: Build APKs (For Each Chipset)
        run: flutter build apk --split-per-abi

      - name: Generate Release Tag
        id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ secrets.TOKEN }}
          version_scheme: semantic
        
      - name: Push APK to Release
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: ${{ steps.compute_tag.outputs.next_tag }}
          token: ${{ secrets.TOKEN }}
